##############################################
######## Analysis Configuration #############

[general]
output = "pi0_mass_peak_selection_2"
primfn = "default_primary_classification"
pidfn = "default_pid"
calofn = "default_calo_ke"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]
recopi0thresh = [
    "@photon_threshold",
    "@leading_photon_threshold",
]

[parameters]
photon_threshold = 20.0
electron_threshold = 0.0
muon_threshold = 143.425
pi0_threshold = 0.0
pion_threshold = 25.0
proton_threshold = 0.0
leading_photon_threshold = 40.0
pi0_mass_veto_low = 0.0
pi0_mass_veto_high = 400.0
flash_low_t = -0.5
flash_high_t = 1.6
bnb_fom2_cut = 0.98


##########################################
######## Sample Definitions ##############

[[sample]]
name = "mc"
# path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input*-reweighted.flat.caf.root"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"
ismc = true
disable = false

[[sample]]
name = "offbeam"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/offbeamlight/*.flat.root"
ismc = false
disable = false

[[sample]]
name = "onbeam"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/devsample/*.flat.root"
ismc = false
disable = false


########################################
######## Tree Definitions ##############

[[tree]]
name = "mc"
sim_only = false 
add_systematics = false
mode = "reco"
cut = [
    {name = "fiducial_cut",             type = "reco"},
    {name = "valid_flashmatch",         type = "reco"},
    {name = "single_muon",              type = "reco",  parameters = ["@muon_threshold"]},
    {name = "no_charged_pions",         type = "reco",  parameters = ["@pion_threshold"]},
    {name = "two_photons",              type = "reco",  parameters = ["@photon_threshold"]},
    {name = "leading_photon_ke_cut",    type = "reco",  parameters = ["@leading_photon_threshold"]},
    {name = "valid_pi0_mass_cut",       type = "reco",  parameters = ["@pi0_mass_veto_low", "@pi0_mass_veto_high"]},
    {name = "neutrino",                 type = "true"}
]
branch = [

    # Interaction-level branches
    { name = "neutrino_id",           type = "true"    },
    { name = "neutrino_energy",       type = "mctruth" },
    { name = "baseline",              type = "mctruth" },
    { name = "cc",                    type = "mctruth" },
    { name = "pdg",                   type = "mctruth" },
    { name = "off_axis_angle",        type = "mctruth" },
    { name = "off_axis_angle_sbnd",   type = "both"    },
    { name = "off_axis_angle_icarus", type = "both"    },
    # { name = "category",              type = "true"    },
    { name = "visible_energy",        type = "both"    },
    { name = "dpT",                   type = "both"    },
    { name = "dalphaT",               type = "both"    },
    { name = "dphiT",                 type = "both"    },
    { name = "dpL",                   type = "both"    },
    { name = "pn",                    type = "both"    },
    { name = "vertex_x",              type = "both"    },
    { name = "vertex_y",              type = "both"    },
    { name = "vertex_z",              type = "both"    },
    { name = "photon_multiplicity",   type = "both",  parameters = [ "@photon_threshold"   ] },
    { name = "electron_multiplicity", type = "both",  parameters = [ "@electron_threshold" ] },
    { name = "pion_multiplicity",     type = "both",  parameters = [ "@pion_threshold"     ] },
    { name = "muon_multiplicity",     type = "both",  parameters = [ "@muon_threshold"     ] },
    { name = "proton_multiplicity",   type = "both",  parameters = [ "@proton_threshold"   ] },

    {name = "pi0_mass", type = "reco"},
    {name = "mass_max", type = "both"},
    {name = "category_topology_ccpi0_simple1", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},
    {name = "category_topology_ccpi0_simple2", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},
    {name = "category_topology_ccpi0_complete", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},

]


[[tree]]
name = "offbeam"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut", type = "reco"},
    {name = "valid_flashmatch", type = "reco"},
    {name = "single_muon", type = "reco", parameters = ["@muon_threshold"]},
    {name = "no_charged_pions", type = "reco", parameters = ["@pion_threshold"]},
    {name = "two_photons", type = "reco", parameters = ["@photon_threshold"]},
    {name = "leading_photon_ke_cut", type = "reco", parameters = ["@leading_photon_threshold"]},
    {name = "valid_pi0_mass_cut", type = "reco", parameters = ["@pi0_mass_veto_low", "@pi0_mass_veto_high"]},
    {name = "cosmic", type = "true"}
]
branch = [

    # Interaction-level branches
    { name = "neutrino_id",           type = "true"    },
    { name = "neutrino_energy",       type = "mctruth" },
    { name = "baseline",              type = "mctruth" },
    { name = "cc",                    type = "mctruth" },
    { name = "pdg",                   type = "mctruth" },
    { name = "off_axis_angle",        type = "mctruth" },
    { name = "off_axis_angle_sbnd",   type = "both"    },
    { name = "off_axis_angle_icarus", type = "both"    },
    # { name = "category",              type = "true"    },
    { name = "visible_energy",        type = "both"    },
    { name = "dpT",                   type = "both"    },
    { name = "dalphaT",               type = "both"    },
    { name = "dphiT",                 type = "both"    },
    { name = "dpL",                   type = "both"    },
    { name = "pn",                    type = "both"    },
    { name = "vertex_x",              type = "both"    },
    { name = "vertex_y",              type = "both"    },
    { name = "vertex_z",              type = "both"    },
    { name = "photon_multiplicity",   type = "both",  parameters = [ "@photon_threshold"   ] },
    { name = "electron_multiplicity", type = "both",  parameters = [ "@electron_threshold" ] },
    { name = "pion_multiplicity",     type = "both",  parameters = [ "@pion_threshold"     ] },
    { name = "muon_multiplicity",     type = "both",  parameters = [ "@muon_threshold"     ] },
    { name = "proton_multiplicity",   type = "both",  parameters = [ "@proton_threshold"   ] },

    {name = "pi0_mass", type = "reco"},
    {name = "mass_max", type = "both"},
    {name = "category_topology_ccpi0_simple1", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},
    {name = "category_topology_ccpi0_simple2", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},
    {name = "category_topology_ccpi0_complete", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},

]


[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    {name = "neutrino", type = "true"},
    {name = "fiducial_cut", type = "true"},
    {name = "iscc", type = "true"},
    {name = "single_muon", type = "true", parameters = ["@muon_threshold"]},
    {name = "no_charged_pions", type = "true", parameters = ["@pion_threshold"]},
    {name = "single_pi0", type = "true", parameters = ["@pi0_threshold"]},
]
branch = [

    # Interaction-level branches
    { name = "neutrino_id",           type = "true"    },
    { name = "neutrino_energy",       type = "mctruth" },
    { name = "baseline",              type = "mctruth" },
    { name = "cc",                    type = "mctruth" },
    { name = "pdg",                   type = "mctruth" },
    { name = "off_axis_angle",        type = "mctruth" },
    { name = "off_axis_angle_sbnd",   type = "both"    },
    { name = "off_axis_angle_icarus", type = "both"    },
    # { name = "category",              type = "true"    },
    { name = "visible_energy",        type = "both"    },
    { name = "dpT",                   type = "both"    },
    { name = "dalphaT",               type = "both"    },
    { name = "dphiT",                 type = "both"    },
    { name = "dpL",                   type = "both"    },
    { name = "pn",                    type = "both"    },
    { name = "vertex_x",              type = "both"    },
    { name = "vertex_y",              type = "both"    },
    { name = "vertex_z",              type = "both"    },
    { name = "photon_multiplicity",   type = "both",  parameters = [ "@photon_threshold"   ] },
    { name = "electron_multiplicity", type = "both",  parameters = [ "@electron_threshold" ] },
    { name = "pion_multiplicity",     type = "both",  parameters = [ "@pion_threshold"     ] },
    { name = "muon_multiplicity",     type = "both",  parameters = [ "@muon_threshold"     ] },
    { name = "proton_multiplicity",   type = "both",  parameters = [ "@proton_threshold"   ] },

    {name = "pi0_mass", type = "reco"},
    {name = "mass_max", type = "both"},
    {name = "category_topology_ccpi0_simple1", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},
    {name = "category_topology_ccpi0_simple2", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},
    {name = "category_topology_ccpi0_complete", type = "true", parameters = ["@photon_threshold", "@electron_threshold", "@muon_threshold", "@pi0_threshold", "@pion_threshold", "@proton_threshold"]},


    # Cuts for efficiency analysis
    {name = "fiducial_cut", type = "both"},
    {name = "valid_flashmatch", type = "reco"},
    {name = "single_muon", type = "reco", parameters = ["@muon_threshold"]},
    {name = "no_charged_pions", type = "reco", parameters = ["@pion_threshold"]},
    #{name = "at_least_two_photons", type = "reco", parameters = ["@photon_threshold"]},
    #{name = "less_than_four_photons", type = "reco", parameters = ["@photon_threshold"]},
    {name = "two_photons", type = "reco", parameters = ["@photon_threshold"]},
    {name = "leading_photon_ke_cut", type = "reco", parameters = ["@leading_photon_threshold"]},
    {name = "valid_pi0_mass_cut", type = "reco", parameters = ["@pi0_mass_veto_low", "@pi0_mass_veto_high"]},
]