[general]
output = "/pnfs/sbnd/scratch/users/rlazur/MCP2025B/ccpi0/pot_5e18/mc_only_flashmatched"

primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

[parameters]
photon_threshold = 20.0
electron_threshold = 0.0
muon_threshold = 143.425
pi0_threshold = 0.0
pion_threshold = 25.0
proton_threshold = 0.0
leading_photon_threshold = 40.0
pi0_mass_veto_low = 0.0
pi0_mass_veto_high = 400.0
flash_low_t = -0.5
flash_high_t = 1.6
bnb_fom2_cut = 0.98

##################################################################################

[[sample]]
name = "mc"
# path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input001-reweighted.flat.caf.root"   # test
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"     # 5e18
ismc = true
disable = false

[[sample]]
name = "onbeam"
# path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/devsample/input000.flat.root"     # test
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/devsample/*.flat.root"        # all
ismc = false
disable = false

[[sample]]
name = "offbeam"
# path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/offbeamlight/input000.flat.root"  # test
# path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/offbeamlight/input00*.flat.root"   # 10 files
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/data/offbeamlight/input*.flat.root"    # 70 files
ismc = false
disable = true

##################################################################################

[[category]] # 0 : Signal: fiducial, cc, single muon, zero charged pions, single pi0
cuts = [
    {name = "neutrino"},
    {name = "iscc"},
    {name = "fiducial_cut"},
    {name = "single_muon", parameters = ["@muon_threshold"]},
    {name = "no_charged_pions", parameters = ["@pion_threshold"]},
    {name = "single_pi0", parameters = ["@pi0_threshold"]},
]
[[category]] # 1 : fiducial, cc, single muon, zero charged pions, at least two pi0s
cuts = [
    {name = "neutrino"},
    {name = "iscc"},
    {name = "fiducial_cut"},
    {name = "single_muon", parameters = ["@muon_threshold"]},
    {name = "no_charged_pions", parameters = ["@pion_threshold"]},
    {name = "!single_pi0", parameters = ["@pi0_threshold"]},
]
[[category]] # 2: fiducial, cc, single muon, at least one charged pion, any number of pi0s
cuts = [
    {name = "neutrino"},
    {name = "iscc"},
    {name = "fiducial_cut"},
    {name = "single_muon", parameters = ["@muon_threshold"]},
    {name = "!no_charged_pions", parameters = ["@pion_threshold"]},
]
[[category]] # 3: fiducial, NC, zero muons, any number of charged pions,
cuts = [
    {name = "!iscc"},
    {name = "fiducial_cut"},
    {name = "no_muons", parameters = ["@muon_threshold"]},
    {name = "!no_charged_pions", parameters = ["@pion_threshold"]},
]
[[category]] # 4: Other neutrino
cuts = [
    {name = "neutrino"},
]
[[category]] # 5: Cosmic
cuts = [
    {name = "!neutrino"},
]

##################################################################################

[[tree]]
name = "selected"
sim_only = false
mode = "reco"
cut = [
    {name = "neutrino", type = "true"},
    {name = "valid_flashmatch", type = "reco"},
]
branch = [

###################################
# True interaction info
{name = "neutrino_id", type = "true"},
{name = "pdg", type = "mctruth"},
{name = "baseline", type = "mctruth"},
{name = "cc", type = "mctruth"},
{name = "neutrino_energy", type = "mctruth"},
{name = "interaction_type", type = "mctruth"},
{name = "interaction_mode", type = "mctruth"},
{name = "category", type = "true"},

###################################
# Event Information
{name = "flash_time", type = "reco"},
{name = "containment", type = "both"},
{name = "fiducial", type = "both"},
{name = "valid_flashmatch", type = "reco"},

###################################
# Pi0 variables
{name = "pi0_mass", type = "both"},
{name = "mass_max", type = "both"},
{name = "pi0_energy", type = "both"},
{name = "pi0_beam_costheta", type = "both"},
{name = "pi0_showers_costheta", type = "both"},
{name = "pi0_momentum", type = "both"},
    
# Leading Shower
{name = "pi0_leading_shower_conv_dist", type = "both"},
{name = "pi0_leading_shower_ke", type = "both"},
    
# Sub-leading Shower
{name = "pi0_subleading_shower_conv_dist", type = "both"},
{name = "pi0_subleading_shower_ke", type = "both"},

###################################
# Kinematics
{name = "vertex_x", type = "both"},
{name = "vertex_y", type = "both"},
{name = "vertex_z", type = "both"},

###################################
# Muon variables
{name = "ke", type = "both_particle", selector = "leading_muon"},
{name = "p", type = "both_particle", selector = "leading_muon"},
{name = "px", type = "both_particle", selector = "leading_muon"},
{name = "py", type = "both_particle", selector = "leading_muon"},
{name = "pz", type = "both_particle", selector = "leading_muon"},
{name = "csda_ke", type = "both_particle", selector = "leading_muon"},
{name = "mcs_ke", type = "both_particle", selector = "leading_muon"},
{name = "start_dedx", type = "reco_particle", selector = "leading_muon"},
{name = "azimuthal_angle", type = "both_particle", selector = "leading_muon"},
{name = "beam_costheta", type = "both_particle", selector = "leading_muon"},
{name = "polar_angle", type = "both_particle", selector = "leading_muon"},
{name = "length", type = "both_particle", selector = "leading_muon"},
{name = "start_x", type = "both_particle", selector = "leading_muon"},
{name = "start_y", type = "both_particle", selector = "leading_muon"},
{name = "start_z", type = "both_particle", selector = "leading_muon"},
{name = "end_x", type = "both_particle", selector = "leading_muon"},
{name = "end_y", type = "both_particle", selector = "leading_muon"},
{name = "end_z", type = "both_particle", selector = "leading_muon"},

# Softmax
{name = "muon_softmax", type = "reco_particle", selector = "leading_muon"},
{name = "pion_softmax", type = "reco_particle", selector = "leading_muon"},
{name = "proton_softmax", type = "reco_particle", selector = "leading_muon"},

###################################
# Interaction variables
{name = "visible_energy", type = "both"},
{name = "Q2", type = "both"},
{name = "W", type = "both"},

###################################
# TKI
{name = "dpT", type = "both"},
{name = "dpT_lp", type = "both"},
{name = "dpL", type = "both"},
{name = "dpL_lp", type = "both"},
{name = "pn", type = "both"},
{name = "pn_lp", type = "both"},
{name = "dphiT", type = "both"},
{name = "dalphaT", type = "both"},
{name = "dalphaT_arg", type = "both"},
]

[[tree]]
name = "selected_cos"
sim_only = false
mode = "reco"
cut = [
    {name = "cosmic", type = "true"},
    {name = "valid_flashmatch", type = "reco"},
]
branch = [

###################################
# True interaction info
{name = "neutrino_id", type = "true"},
{name = "pdg", type = "mctruth"},
{name = "baseline", type = "mctruth"},
{name = "cc", type = "mctruth"},
{name = "neutrino_energy", type = "mctruth"},
{name = "interaction_type", type = "mctruth"},
{name = "interaction_mode", type = "mctruth"},
{name = "valid_flashmatch", type = "reco"},
    
###################################
# Event Information
{name = "flash_time", type = "reco"},
{name = "containment", type = "both"},
{name = "fiducial", type = "both"},
{name = "category", type = "true"},

###################################
# Pi0 variables
{name = "pi0_mass", type = "both"},
{name = "mass_max", type = "both"},
{name = "pi0_energy", type = "both"},
{name = "pi0_beam_costheta", type = "both"},
{name = "pi0_showers_costheta", type = "both"},
{name = "pi0_momentum", type = "both"},

###################################
# Leading Shower
{name = "pi0_leading_shower_conv_dist", type = "both"},
{name = "pi0_leading_shower_ke", type = "both"},

###################################
# Sub-leading Shower
{name = "pi0_subleading_shower_conv_dist", type = "both"},
{name = "pi0_subleading_shower_ke", type = "both"},

###################################
# Kinematics
{name = "vertex_x", type = "both"},
{name = "vertex_y", type = "both"},
{name = "vertex_z", type = "both"},

###################################
# Muon variables
{name = "ke", type = "both_particle", selector = "leading_muon"},
{name = "p", type = "both_particle", selector = "leading_muon"},
{name = "px", type = "both_particle", selector = "leading_muon"},
{name = "py", type = "both_particle", selector = "leading_muon"},
{name = "pz", type = "both_particle", selector = "leading_muon"},
{name = "csda_ke", type = "both_particle", selector = "leading_muon"},
{name = "mcs_ke", type = "both_particle", selector = "leading_muon"},
{name = "start_dedx", type = "reco_particle", selector = "leading_muon"},
{name = "azimuthal_angle", type = "both_particle", selector = "leading_muon"},
{name = "beam_costheta", type = "both_particle", selector = "leading_muon"},
{name = "polar_angle", type = "both_particle", selector = "leading_muon"},
{name = "length", type = "both_particle", selector = "leading_muon"},
{name = "start_x", type = "both_particle", selector = "leading_muon"},
{name = "start_y", type = "both_particle", selector = "leading_muon"},
{name = "start_z", type = "both_particle", selector = "leading_muon"},
{name = "end_x", type = "both_particle", selector = "leading_muon"},
{name = "end_y", type = "both_particle", selector = "leading_muon"},
{name = "end_z", type = "both_particle", selector = "leading_muon"},

# Softmax
{name = "muon_softmax", type = "reco_particle", selector = "leading_muon"},
{name = "pion_softmax", type = "reco_particle", selector = "leading_muon"},
{name = "proton_softmax", type = "reco_particle", selector = "leading_muon"},

###################################
# Interaction variables
{name = "visible_energy", type = "both"},
{name = "Q2", type = "both"},
{name = "W", type = "both"},

###################################
# TKI
{name = "dpT", type = "both"},
{name = "dpT_lp", type = "both"},
{name = "dpL", type = "both"},
{name = "dpL_lp", type = "both"},
{name = "pn", type = "both"},
{name = "pn_lp", type = "both"},
{name = "dphiT", type = "both"},
{name = "dalphaT", type = "both"},
{name = "dalphaT_arg", type = "both"},

]
